apiVersion: v1
kind: Service
metadata:
  name: {{ include "binwatch.fullname" . }}-headless
  labels:
    {{- include "binwatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "binwatch.selectorLabels" . | nindent 4 }}