---
logger:
  # debug, info, warn, error, dpanic, panic, fatal
  level: debug
  # console or json
  encoding: json

sources:
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "MiContrasenaSegura"
    server_id: 100
    read_timeout: 90
    heartbeat_period: 60
    flavor: mysql
    sync_timeout_ms: 200
    # Just listen for events in this database-table pairs
    filter_tables:
      - database: test
        table: test

connectors:
  data: |
    {{- printf `{ "index": "test", "id": %v, "data": %s}` .data.id (toJson .data) }}

  pubsub:
    project_id: "test-project"
    topic_id: "test-topic"

  webhook:
    tls_skip_verify: false
    url: "https://webhook.site/id"
    method: "POST"
    headers:
      X-BinWatch: "true"