---
# BinWatch configuration file
# This file is written in YAML format

# Logger configuration
logger:
  # debug, info, warn, error, dpanic, panic, fatal
  level: debug
  # console or json
  encoding: json

hashring:
  sync_worker_time_ms: 300

  # Environment variable to determine if this node has to execute the sync worker
  env_flag: "HOSTNAME"

  # For static ring discovery we need to define the hostname of the nodes, so we will check if
  # $HOSTNAME env variable (by default) is the same as configured here.
  static_ring_discovery:
    hosts:
    - test
    - test2

  # For DNS ring discovery we need to define the domain and the port of the headless service to get
  # the list of nodes.
#  dns_ring_discovery:
#    domain: "dns.example.com"

# Sources configuration
# List of sources to watch for changes in the database binlog
sources:

  # MySQL source configuration
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "MiContrasenaSegura"

    # Server ID must be unique across all MySQL servers
    server_id: 100

    # Read timeout in seconds
    read_timeout: 90

    # Heartbeat period in seconds
    heartbeat_period: 60

    # Flavor of the database. MySQL or MariaDB
    flavor: mysql

    # Timeout for syincing the events in milliseconds
    sync_timeout_ms: 200

    # Just listen for events in this database-table pairs
    filter_tables:
      - database: test
        table: test

# Data connectors configuration
# List of connectors to send the data to
connectors:

  # Data format to send to the connector. Helm Templating is supported
  data: |
    {{- printf `{ "index": "test", "id": %v, "data": %s}` .data.id (toJson .data) }}

  # PubSub connector configuration
  pubsub:
    project_id: "test-project"
    topic_id: "test-topic"

  # Webhook connector configuration
  webhook:
    tls_skip_verify: false
    url: "https://webhook.site/4d857c1c-9162-4858-b2db-f056f79b24f6"
    method: "POST"
    headers:
      X-BinWatch: "true"