services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql-binlog-watch-row
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MiContrasenaSegura
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=MiContrasenaSegura"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis-binlog-watch-row
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: